# -*- coding: utf-8 -*-
"""Processing1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K1n4ZoWXQQeNJmqR-PAGxKC45X4XhGZv
"""

# Vivian Luu
# 2/16/2024
# An if decsision is a decsion that will either run specific code or not if a condition is met.
# An if else decision is a decsion that can run different sets of code based on whether or not the condition is met.
# A condition is a statement we can use to make decisions. The condition could be whether a variable is above, below, or equal to a number or even a combination of those.
# A different condition could be whether the varible is or is not the type you're looking for. There can also be multiple conditions that need to be met.
# Using if and if else, we can use the conditions to make decisions which will decide whether to run a block of code, or which blocks of code to run.
# Using a while loop, we can use the condion to make a decision on whether or not to keep repeating the loop.
# The key differences between a while loop and a for loop is how we control how long they repeat. In a for loop, you can tell the loop how many repetitions it does.
# This can be done with a variable or manually putting a number. In a while loop the loop will continue repeating until a condition is met or it can go on infinitely.

#Problem 1

x = input("Please type an integer, x is")
y = input("Please type another integer, y is")
if x > y:
  print("X is larger than Y")

#Problem 2

x = input("Please type an integer, x is")
y = input("Please type another integer, y is")
if x > y:
  print("X is larger than Y")
else:
  print("Y is larger than X")

#Problem 3

x = input("Please type an integer, x = ")
y = input("Please type another integer, y = ")
if x > y:
  print("X is larger than Y")
elif y > x:
  print("Y is larger than X")
else:
  print("X and Y are equal")

#Problem 4

n = 0
while n < 100:
  n += 1
  print(n)

n = 101
while n > 1:
  n -= 1
  print(n)

#Problem 5

for n in (range(1,101,1)):
  print(n)

for n in (range(100,0,-1)):
  print(n)

#Problem 6

for n in (range(10,101)):
  print(n)

#Problem 7

for n in (range(10,110,10)):
  print(n)

#Problem 8

lst = ["Bob", "Smith", "1234 Noplace Street", "Nowhere", "UT", "8499"]
for n in lst:
  print(n)

#Problem 9

age = input("Please type your age: ")
age = int(age)
while age < 1 or age > 125:
  age = input("Please type your actual age: ")
  age = int(age)
print("Your age was:",age)